{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-job-launcher.serviceAccountName" . }}
  labels:
    {{- include "k8s-job-launcher.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-job-launcher.fullname" . }}
  labels:
    {{- include "k8s-job-launcher.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]

- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["list"]

- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-job-launcher.fullname" . }}
  labels:
    {{- include "k8s-job-launcher.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-job-launcher.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "k8s-job-launcher.fullname" . }}
  apiGroup: rbac.authorization.k8s.io









